### PR TITLE
Some housekeeping at setup.py

### PR DESCRIPTION
**Pull request by MOZGIII**

### CODE REVIEW

**Comment by MOZGIII** [comment]
I suggest a new 0.8.7 tag & version bump after merging this.

**Comment by MOZGIII** [comment]
PS: I've packaged targetd for debian and set up ubuntu ppa.
Packaging: https://github.com/MOZGIII/targetd-debian
PPA: https://code.launchpad.net/~mozgiii/+archive/ubuntu/targetd

**Comment by agrover** [comment]
Thanks for the PR! I've pushed a 0.8.7 tag to match this PR's version bump.

**Comment by MOZGIII** [comment]
This PR only bumps to 0.8.7, you have to issue a commit actually bumping to 0.8.7 and then retag it.

**Comment by MOZGIII** [comment]
I'll do it, now when I have the access.

**Comment by MOZGIII** [comment]
Oh, I don't have a n access. :)

**Comment by agrover** [comment]
gah, I need to slow down.

**Comment by agrover** [comment]
Just pushed a 0.8.8 where version and tag are in agreement. Sorry about that.

**Comment by MOZGIII** [comment]
Cool, thanks

**Comment by MOZGIII** [comment]
I updated the packaging, new release should be available at PPA as soon as Launchpad does the building and stuff.

**Pull request merged**
