### PR TITLE
content of Dockerfile assume that there is in a project root

### PR DESCRIPTION
**Pull request by whywaita**
for example,

https://github.com/open-iscsi/targetd/blob/d7888bb4bede5416c078c3bdea2e705f69049a03/docker/Dockerfile#L29

```
RUN python3 setup.py install
```

`setup.py` is in a project root.

### CODE REVIEW

**Comment by tasleson** [comment]
What we have works, eg. `$ podman build -t "whatever" -f docker/Dockerfile .`

I would prefer to keep the docker stuff out of project root directory if possible.

@Queuecumber You added `Dockerfile`, comments/suggestions on this?

**Comment by Queuecumber** [comment]
I'm not sure I understand the problem this is solving, afaik what we had was working fine but I'll double check it today

**Comment by whywaita** [comment]
@tasleson @Queuecumber Thank you for your check!

I tried your suggestions command, so successfully.
So I think to revert commit and write an example of docker build command to README.

What do you think?

**Comment by tasleson** [comment]
@whywaita 
>So I think to revert commit and write an example of docker build command to README.
> What do you think?

Sounds good, thanks!

**Comment by whywaita** [comment]
@tasleson Thanks!

commit updated, plz check me :)

**Comment by tasleson** [comment]
Looks good, I removed the first 2 commits and merged your branch, thanks!

**Comment by whywaita** [comment]
okay, thank you!

**Pull request closed without merging**
