### PR TITLE
Security improvements

### PR DESCRIPTION
**Pull request by tasleson**
Address two potential issues:

1. Client sending excessive amounts of data in a request
2. Password brute force attacks

Resolves: https://github.com/open-iscsi/targetd/issues/66

### CODE REVIEW

**Comment by tasleson** [comment]
@dsonck92 If you have the time I would appreciate looking this over, thanks.

**Review by Jamalx1x — APPROVED** [review]

**Comment by dsonck92** [comment]
Looks good regarding the payload size. Regarding the password delay: Nothing is preventing users from connecting in parallel and executing multiple passwords. Maybe a fail2ban style approach might be more effective, i.e. let a specific IP/user or combination thereof try a fixed amount of times before ignoring it for a fixed timespan (probably both configurable). This would not stop a distributed attack but it would help mitigate an attempt from one location.

**Comment by tasleson** [comment]
@dsonck92 I'll see what I can add to mitigate a parallel attack.

**Comment by tasleson** [comment]
@dsonck92 Updated PR to prevent concurrent failed authentication attempts from same IP.

**Review by dsonck92 — APPROVED** [review]
Looks good to me, it should be more effective now against the parallel attempts.

I still think it might be worthwhile to look into existing authentication systems in the future so "those who know best" can deal with the problem of authentication. But for now this is better than no protection.

**Comment by tasleson** [comment]
@dsonck92 Thanks for the review

**Review by Jamalx1x — APPROVED** [review]

**Pull request merged**
